In [1]:
import pandas as pd
import numpy as np

In [27]:
# Read the raw data
df = pd.read_csv("dirty_data.csv")
print(df, '\n')
print(df.info())

   ID         Name    Age  Gender         Salary    JoinDate
0   1         Anna   29.0  Female          55000  2020-01-15
1   1         Anna   29.0  Female          55000  2020-01-15
2   2          Bob    NaN    male          62000  2021-05-20
3   3        Cindy   22.0  female  not available  2019-11-01
4   4    donald      29.0    Male          55000  2020-01-15
5   5         emma  130.0  Female          72000  2022-07-30
6   6        Frank   35.0    Male          68000         NaN
7   7       Gordon    NaN    Male          75000  2018-03-12

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        8 non-null      int64
 1   Name      8 non-null      object
 2   Age       6 non-null      float64
 3   Gender    8 non-null      object
 4   Salary    8 non-null      object
 5   JoinDate  7 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 516.0+ bytes
None

In [28]:
# Check for duplicate rows

duplicate_rows = df[df.duplicated()]
print("\nDuplicate rows (excluding first occurrence):")
print(duplicate_rows, '\n')

# Count missing values per column
print("Number of missing values of each column:\n", df.isna().sum())

Duplicate rows (excluding first occurrence):
   ID  Name   Age  Gender Salary    JoinDate
1   1  Anna  29.0  Female  55000  2020-01-15

Number of missing values of each column:
 ID          0
Name        0
Age         2
Gender      0
Salary      0
JoinDate    1
dtype: int64

In [29]:
# Remove duplicate rows
df = df.drop_duplicates()

# Handling Missing Values
df['Age'] = df['Age'].fillna(df['Age'].median())  # เติม median ของ Age
df['JoinDate'] = df['JoinDate'].fillna("2020-01-01")  # เติม default date

df['Salary'] = df['Salary'].replace("not available", np.nan)  # แปลง not available เป็น NaN
df['Salary'] = df['Salary'].astype(float)  # แปลง Salary เป็น float
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())  # เติม mean ของ Salary

print(df)

   ID         Name    Age  Gender   Salary    JoinDate
0   1         Anna   29.0  Female  55000.0  2020-01-15
2   2          Bob   29.0    male  62000.0  2021-05-20
3   3        Cindy   22.0  female  64500.0  2019-11-01
4   4    donald      29.0    Male  55000.0  2020-01-15
5   5         emma  130.0  Female  72000.0  2022-07-30
6   6        Frank   35.0    Male  68000.0  2020-01-01
7   7       Gordon   29.0    Male  75000.0  2018-03-12

In [30]:
# Format the strings: remove trailing space and capitalize the words
df['Name'] = df['Name'].str.strip()  # ตัดช่องว่าง
df['Name'] = df['Name'].str.capitalize()  # ทำให้เป็นตัวพิมพ์ใหญ่ตัวแรก
df['Gender'] = df['Gender'].str.capitalize()  # ทำให้เป็นตัวพิมพ์ใหญ่ตัวแรก

# Change Gender to be Category for more efficient further processing
df['Gender'] = df['Gender'].astype('category')

# Handle Outliers (Age > 110 is considered an outlier)
df.loc[df['Age'] > 110, 'Age'] = df['Age'].median()

# Show the cleaned dataset
print("\nCleaned data")
print(df, '\n')
print(df.info())

Cleaned data
   ID    Name   Age  Gender   Salary    JoinDate
0   1    Anna  29.0  Female  55000.0  2020-01-15
2   2     Bob  29.0    Male  62000.0  2021-05-20
3   3   Cindy  22.0  Female  64500.0  2019-11-01
4   4  Donald  29.0    Male  55000.0  2020-01-15
5   5    Emma  29.0  Female  72000.0  2022-07-30
6   6   Frank  35.0    Male  68000.0  2020-01-01
7   7  Gordon  29.0    Male  75000.0  2018-03-12

<class 'pandas.core.frame.DataFrame'>
Index: 7 entries, 0 to 7
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        7 non-null      int64
 1   Name      7 non-null      object
 2   Age       7 non-null      float64
 3   Gender    7 non-null      category
 4   Salary    7 non-null      float64
 5   JoinDate  7 non-null      object
dtypes: category(1), float64(2), int64(1), object(2)
memory usage: 467.0+ bytes
None

In [31]:
df

   ID    Name   Age  Gender   Salary    JoinDate
0   1    Anna  29.0  Female  55000.0  2020-01-15
2   2     Bob  29.0    Male  62000.0  2021-05-20
3   3   Cindy  22.0  Female  64500.0  2019-11-01
4   4  Donald  29.0    Male  55000.0  2020-01-15
5   5    Emma  29.0  Female  72000.0  2022-07-30
6   6   Frank  35.0    Male  68000.0  2020-01-01
7   7  Gordon  29.0    Male  75000.0  2018-03-12

In [34]:
# Impute numerical values with mean, "If its skew is not much and with few outliers"
df.loc[:, 'Age'] = df['Age'].fillna(df['Age'].mean())

In [35]:
# Impute numerical values with median, if it's highly skewed or having lots of outliers
df.loc[:, 'Salary'] = df['Salary'].fillna(df['Salary'].median())

In [36]:
# Impute categorical values with mode
df.loc[:, 'Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])

In [37]:
df

   ID    Name   Age  Gender   Salary    JoinDate
0   1    Anna  29.0  Female  55000.0  2020-01-15
2   2     Bob  29.0    Male  62000.0  2021-05-20
3   3   Cindy  22.0  Female  64500.0  2019-11-01
4   4  Donald  29.0    Male  55000.0  2020-01-15
5   5    Emma  29.0  Female  72000.0  2022-07-30
6   6   Frank  35.0    Male  68000.0  2020-01-01
7   7  Gordon  29.0    Male  75000.0  2018-03-12